### ISSUE TITLE
video tests fail if ffmpeg/ffprobe are not in PATH

### ISSUE THREAD

**Issue by rathann** [niol/lazygal#7]
The code in [mediautils.py:35](https://github.com/niol/lazygal/blob/master/lazygal/mediautils.py#L35) appears to "detect" FFmpeg presence, but doesn't seem to use the result of the test. The testsuite is then failing if `ffmpeg` or `ffprobe` binaries are not in `PATH`:

```
======================================================================
ERROR: test_video (lazygaltest.test_metadata.TestFileMetadata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lazygal-0.10/lazygaltest/test_metadata.py", line 260, in test_video
    vid_md = metadata.VideoInfoTags(self.get_sample_path(sample))
  File "/builddir/build/BUILD/lazygal-0.10/lazygal/metadata.py", line 444, in __init__
    videoinfo = mediautils.VideoInfo(path).inspect()
  File "/builddir/build/BUILD/lazygal-0.10/lazygal/mediautils.py", line 103, in inspect
    info = subprocess.check_output(['ffprobe', '-v', 'error',
  File "/usr/lib64/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

======================================================================
ERROR: test_withvideo (lazygaltest.test_generators.TestGenerators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lazygal-0.10/lazygaltest/test_generators.py", line 604, in test_withvideo
    silencer.convert(os.path.join(source_subgal.path, 'vid-silent.mov'))
  File "/builddir/build/BUILD/lazygal-0.10/lazygal/mediautils.py", line 86, in convert
    logging.debug('RUNNING %s' % ' '.join(runcmd))
TypeError: sequence item 0: expected str instance, NoneType found
```

I guess I'm requesting for the above two tests to be skipped if FFmpeg is not installed. FFmpeg can't be included in official Fedora repositories for legal reasons, so I don't have the option to have FFmpeg installed when building the official Fedora lazygal package.

**Comment by rathann** [comment]
This works great, thanks for the quick fix.

**Comment by niol** [comment]
Thanks a lot for reporting.
