### ISSUE TITLE
Exception "adding same dep twice" 

### ISSUE THREAD

**Issue by glubsy** [niol/lazygal#9]
lazygal version 0.10 from debian testing repo.
Generating from a directory, the program starts adding files and then raises an exception:
```
> lazygal /target
[Entering %ALBUMROOT%/]
[...]
Progress: dir 0/1 (0%), media 0/403 (0%)Traceback (most recent call last):
  File "/usr/bin/lazygal", line 294, in <module>
    album.generate(progress=progress)
  File "/usr/lib/python3/dist-packages/lazygal/generators.py", line 943, in generate
    destgal.make()
  File "/usr/lib/python3/dist-packages/lazygal/generators.py", line 667, in make
    super().make(force)
  File "/usr/lib/python3/dist-packages/lazygal/make.py", line 120, in make
    self.call_populate_deps()
  File "/usr/lib/python3/dist-packages/lazygal/make.py", line 43, in call_populate_deps
    self.populate_deps()
  File "/usr/lib/python3/dist-packages/lazygal/generators.py", line 367, in populate_deps
    media_task = WebalbumImageTask(self, media)
  File "/usr/lib/python3/dist-packages/lazygal/generators.py", line 260, in __init__
    super().__init__(webgal, image)
  File "/usr/lib/python3/dist-packages/lazygal/generators.py", line 216, in __init__
    self.browse_pages[size_name] = self.get_browse_page(size_name)
  File "/usr/lib/python3/dist-packages/lazygal/generators.py", line 247, in get_browse_page
    return genpage.WebalbumBrowsePage(self.webgal, size_name, self)
  File "/usr/lib/python3/dist-packages/lazygal/genpage.py", line 96, in __init__
    self.add_dependency(self.webalbum_media.original)
  File "/usr/lib/python3/dist-packages/lazygal/make.py", line 57, in add_dependency
    raise RuntimeError('adding same dep twice')
```
All dependencies have been installed: `apt install -t testing ffmpeg exiv2 doc-base python-genshi-doc python-pil-doc python3-pil-dbg`
I have not looked into this very deeply, sorry.

**Comment by niol** [comment]
Thanks a lot for reporting.
What config or command line arguments do you use? I did not manage to reproduce.
Maybe the following change can help...

```diff
--- a/lazygal/genpage.py
+++ b/lazygal/genpage.py
@@ -92,7 +92,8 @@ class WebalbumBrowsePage(WebalbumPage):
         super().__init__(dir, size_name, self.media.name)

         self.add_dependency(self.webalbum_media.resized[size_name])
-        if webalbum_media.original:
+        if webalbum_media.original \
+        and self.dir.newsizers[size_name] != 'original':
             self.add_dependency(self.webalbum_media.original)

         # Depends on source directory in case an image was deleted
```

**Comment by glubsy** [comment]
I was just testing lazygal with no particular command line argument apart from the directory to scan as shown above.
With `--debug` I get this extra line which may or may not indicate something?
```
  Trying loading gallery configs:
PersistentIndex(b'/lazygal_output/index.json') build needed: never built
```
Applying the patch above didn't change anything, I get the same error.

**Comment by niol** [comment]
This should fix the issue.

**Comment by glubsy** [comment]
Thanks for the fix, it seems to work just fine now. :+1:
